name: Gomobile for iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build library for iOS with gomobile
    runs-on: macos-latest

    steps:
      - name: Set up xcode 14.2
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1
        with:
          xcode-version: 14.2
        id: xcode

      - name: Set up Go 1.x
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: ^1.16
        id: go

      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - name: Build
        env:
          platform: ${{ 'iOS Simulator' }}
        run: |
          for d in $ANDROID_NDK_HOME/../23*; do
            ANDROID_NDK_HOME=$d
          done
          ./build.sh apple
          find dist

      - name: Upload xcframework
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          name: gopenpgp.xcframework
          path: dist/apple/gopenpgp.xcframework
          if-no-files-found: error
